/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;


import Database.LivroDAO;
import Bussiness.Livro;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Feh
 */
public class books_view extends javax.swing.JFrame {

    
    /**
     * Creates new form books_view
     */
    public books_view() {
        initComponents();
        desativaBotao();
        desativaTexto();
        setLocationRelativeTo(null);
    }

    public ArrayList<Livro> livros = new ArrayList<>();

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCadastro = new javax.swing.JTable();
        lblFecharX = new javax.swing.JLabel();
        lblFechar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnBusca = new javax.swing.JButton();
        btnBiblioteca = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnCadastrarLivros = new javax.swing.JButton();
        btnFunc = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnEmprestimo = new javax.swing.JButton();
        btnGerarRelat = new javax.swing.JButton();
        pnlBuscarFunc = new javax.swing.JPanel();
        txtBuscarLivros = new javax.swing.JTextField();
        pnlBuscar = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        pnTitulo = new javax.swing.JPanel();
        txtCodigo = new javax.swing.JTextField();
        pnlNome = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JTextField();
        pnlDataNasci = new javax.swing.JPanel();
        txtSubtitulo = new javax.swing.JTextField();
        pnlCPF = new javax.swing.JPanel();
        txtAutor = new javax.swing.JTextField();
        pnlEmail = new javax.swing.JPanel();
        txtEditora = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnExcluir = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnCadastrar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pnlEmail1 = new javax.swing.JPanel();
        txtDataPubli = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(756, 791));

        tbCadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "Subtítulo", "Autor", "Editora", "Data da Publicação"
            }
        ));
        tbCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCadastroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCadastro);

        lblFecharX.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        lblFecharX.setForeground(new java.awt.Color(92, 95, 98));
        lblFecharX.setText("X");
        lblFecharX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFecharXMouseClicked(evt);
            }
        });

        lblFechar.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        lblFechar.setForeground(new java.awt.Color(92, 95, 98));
        lblFechar.setText("Fechar");
        lblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFecharMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 120, 156));
        jLabel1.setText("Cadastrar Livros");

        jPanel1.setBackground(new java.awt.Color(239, 236, 228));
        jPanel1.setPreferredSize(new java.awt.Dimension(218, 799));

        btnInicio.setBackground(new java.awt.Color(239, 236, 228));
        btnInicio.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(60, 65, 70));
        btnInicio.setText("Início");
        btnInicio.setBorder(null);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnBusca.setBackground(new java.awt.Color(239, 236, 228));
        btnBusca.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnBusca.setForeground(new java.awt.Color(60, 65, 70));
        btnBusca.setText("Buscar");
        btnBusca.setBorder(null);
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });

        btnBiblioteca.setBackground(new java.awt.Color(239, 236, 228));
        btnBiblioteca.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnBiblioteca.setForeground(new java.awt.Color(60, 65, 70));
        btnBiblioteca.setText("Biblioteca");
        btnBiblioteca.setBorder(null);
        btnBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBibliotecaActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(102, 120, 156));

        btnCadastrarLivros.setBackground(new java.awt.Color(239, 236, 228));
        btnCadastrarLivros.setFont(new java.awt.Font("Poppins SemiBold", 1, 18)); // NOI18N
        btnCadastrarLivros.setForeground(new java.awt.Color(102, 120, 156));
        btnCadastrarLivros.setText("Cadastrar Livros");
        btnCadastrarLivros.setBorder(null);
        btnCadastrarLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarLivrosActionPerformed(evt);
            }
        });

        btnFunc.setBackground(new java.awt.Color(239, 236, 228));
        btnFunc.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnFunc.setForeground(new java.awt.Color(60, 65, 70));
        btnFunc.setText("Funcionários");
        btnFunc.setBorder(null);
        btnFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncActionPerformed(evt);
            }
        });

        btnClientes.setBackground(new java.awt.Color(239, 236, 228));
        btnClientes.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(60, 65, 70));
        btnClientes.setText("Clientes");
        btnClientes.setBorder(null);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnEmprestimo.setBackground(new java.awt.Color(239, 236, 228));
        btnEmprestimo.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnEmprestimo.setForeground(new java.awt.Color(60, 65, 70));
        btnEmprestimo.setText("Empréstimo");
        btnEmprestimo.setBorder(null);
        btnEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestimoActionPerformed(evt);
            }
        });

        btnGerarRelat.setBackground(new java.awt.Color(239, 236, 228));
        btnGerarRelat.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnGerarRelat.setForeground(new java.awt.Color(60, 65, 70));
        btnGerarRelat.setText("Gerar Relatórios");
        btnGerarRelat.setBorder(null);
        btnGerarRelat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnCadastrarLivros))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnFunc))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnClientes))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnEmprestimo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnGerarRelat))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBusca)
                            .addComponent(btnInicio)
                            .addComponent(btnBiblioteca))))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(btnInicio)
                .addGap(56, 56, 56)
                .addComponent(btnBusca)
                .addGap(55, 55, 55)
                .addComponent(btnBiblioteca)
                .addGap(48, 48, 48)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnCadastrarLivros)
                .addGap(75, 75, 75)
                .addComponent(btnFunc)
                .addGap(72, 72, 72)
                .addComponent(btnClientes)
                .addGap(70, 70, 70)
                .addComponent(btnEmprestimo)
                .addGap(75, 75, 75)
                .addComponent(btnGerarRelat))
        );

        pnlBuscarFunc.setBackground(new java.awt.Color(240, 241, 242));
        pnlBuscarFunc.setPreferredSize(new java.awt.Dimension(408, 38));

        txtBuscarLivros.setBackground(new java.awt.Color(240, 241, 242));
        txtBuscarLivros.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        txtBuscarLivros.setForeground(new java.awt.Color(92, 95, 98));
        txtBuscarLivros.setBorder(null);
        txtBuscarLivros.setCaretColor(new java.awt.Color(92, 95, 98));
        txtBuscarLivros.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarLivrosFocusGained(evt);
            }
        });

        javax.swing.GroupLayout pnlBuscarFuncLayout = new javax.swing.GroupLayout(pnlBuscarFunc);
        pnlBuscarFunc.setLayout(pnlBuscarFuncLayout);
        pnlBuscarFuncLayout.setHorizontalGroup(
            pnlBuscarFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarFuncLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtBuscarLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlBuscarFuncLayout.setVerticalGroup(
            pnlBuscarFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarFuncLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtBuscarLivros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlBuscar.setBackground(new java.awt.Color(60, 65, 70));
        pnlBuscar.setForeground(new java.awt.Color(255, 255, 255));
        pnlBuscar.setPreferredSize(new java.awt.Dimension(0, 38));

        btnBuscar.setBackground(new java.awt.Color(60, 65, 70));
        btnBuscar.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(null);

        javax.swing.GroupLayout pnlBuscarLayout = new javax.swing.GroupLayout(pnlBuscar);
        pnlBuscar.setLayout(pnlBuscarLayout);
        pnlBuscarLayout.setHorizontalGroup(
            pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlBuscarLayout.setVerticalGroup(
            pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnTitulo.setBackground(new java.awt.Color(240, 241, 242));
        pnTitulo.setPreferredSize(new java.awt.Dimension(408, 38));

        txtCodigo.setBackground(new java.awt.Color(240, 241, 242));
        txtCodigo.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(92, 95, 98));
        txtCodigo.setBorder(null);
        txtCodigo.setCaretColor(new java.awt.Color(92, 95, 98));
        txtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoFocusGained(evt);
            }
        });
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTituloLayout = new javax.swing.GroupLayout(pnTitulo);
        pnTitulo.setLayout(pnTituloLayout);
        pnTituloLayout.setHorizontalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTituloLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnTituloLayout.setVerticalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTituloLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlNome.setBackground(new java.awt.Color(240, 241, 242));
        pnlNome.setPreferredSize(new java.awt.Dimension(426, 38));

        txtTitulo.setBackground(new java.awt.Color(240, 241, 242));
        txtTitulo.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(92, 95, 98));
        txtTitulo.setBorder(null);
        txtTitulo.setCaretColor(new java.awt.Color(92, 95, 98));
        txtTitulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTituloFocusGained(evt);
            }
        });

        javax.swing.GroupLayout pnlNomeLayout = new javax.swing.GroupLayout(pnlNome);
        pnlNome.setLayout(pnlNomeLayout);
        pnlNomeLayout.setHorizontalGroup(
            pnlNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNomeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlNomeLayout.setVerticalGroup(
            pnlNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNomeLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDataNasci.setBackground(new java.awt.Color(240, 241, 242));
        pnlDataNasci.setPreferredSize(new java.awt.Dimension(408, 38));

        txtSubtitulo.setBackground(new java.awt.Color(240, 241, 242));
        txtSubtitulo.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        txtSubtitulo.setForeground(new java.awt.Color(92, 95, 98));
        txtSubtitulo.setBorder(null);
        txtSubtitulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSubtituloFocusGained(evt);
            }
        });

        javax.swing.GroupLayout pnlDataNasciLayout = new javax.swing.GroupLayout(pnlDataNasci);
        pnlDataNasci.setLayout(pnlDataNasciLayout);
        pnlDataNasciLayout.setHorizontalGroup(
            pnlDataNasciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDataNasciLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlDataNasciLayout.setVerticalGroup(
            pnlDataNasciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDataNasciLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCPF.setBackground(new java.awt.Color(240, 241, 242));
        pnlCPF.setPreferredSize(new java.awt.Dimension(408, 38));

        txtAutor.setBackground(new java.awt.Color(240, 241, 242));
        txtAutor.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        txtAutor.setForeground(new java.awt.Color(92, 95, 98));
        txtAutor.setBorder(null);
        txtAutor.setCaretColor(new java.awt.Color(92, 95, 98));
        txtAutor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAutorFocusGained(evt);
            }
        });

        javax.swing.GroupLayout pnlCPFLayout = new javax.swing.GroupLayout(pnlCPF);
        pnlCPF.setLayout(pnlCPFLayout);
        pnlCPFLayout.setHorizontalGroup(
            pnlCPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCPFLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlCPFLayout.setVerticalGroup(
            pnlCPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCPFLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlEmail.setBackground(new java.awt.Color(240, 241, 242));
        pnlEmail.setPreferredSize(new java.awt.Dimension(408, 38));

        txtEditora.setBackground(new java.awt.Color(240, 241, 242));
        txtEditora.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        txtEditora.setForeground(new java.awt.Color(92, 95, 98));
        txtEditora.setBorder(null);
        txtEditora.setCaretColor(new java.awt.Color(92, 95, 98));
        txtEditora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEditoraFocusGained(evt);
            }
        });
        txtEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEmailLayout = new javax.swing.GroupLayout(pnlEmail);
        pnlEmail.setLayout(pnlEmailLayout);
        pnlEmailLayout.setHorizontalGroup(
            pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmailLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlEmailLayout.setVerticalGroup(
            pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmailLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 120, 156));

        btnEditar.setBackground(new java.awt.Color(102, 120, 156));
        btnEditar.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.setBorder(null);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(102, 120, 156));

        btnExcluir.setBackground(new java.awt.Color(102, 120, 156));
        btnExcluir.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.setBorder(null);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setBackground(new java.awt.Color(102, 120, 156));

        btnCadastrar.setBackground(new java.awt.Color(102, 120, 156));
        btnCadastrar.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setBorder(null);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.setBackground(new java.awt.Color(102, 120, 156));
        jPanel6.setPreferredSize(new java.awt.Dimension(123, 30));

        btnSalvar.setBackground(new java.awt.Color(102, 120, 156));
        btnSalvar.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(null);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.setBackground(new java.awt.Color(102, 120, 156));
        jPanel7.setPreferredSize(new java.awt.Dimension(123, 30));

        btnCancelar.setBackground(new java.awt.Color(102, 120, 156));
        btnCancelar.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Buscar Livros");

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Código");

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Subtítulo");

        jLabel11.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Autor");

        jLabel12.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Editora");

        jLabel13.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Título");

        pnlEmail1.setBackground(new java.awt.Color(240, 241, 242));
        pnlEmail1.setPreferredSize(new java.awt.Dimension(408, 38));

        txtDataPubli.setBackground(new java.awt.Color(240, 241, 242));
        txtDataPubli.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        txtDataPubli.setForeground(new java.awt.Color(92, 95, 98));
        txtDataPubli.setBorder(null);
        txtDataPubli.setCaretColor(new java.awt.Color(92, 95, 98));
        txtDataPubli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDataPubliFocusGained(evt);
            }
        });
        txtDataPubli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataPubliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEmail1Layout = new javax.swing.GroupLayout(pnlEmail1);
        pnlEmail1.setLayout(pnlEmail1Layout);
        pnlEmail1Layout.setHorizontalGroup(
            pnlEmail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmail1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtDataPubli, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlEmail1Layout.setVerticalGroup(
            pnlEmail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmail1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtDataPubli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Data de Publicação");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(444, 444, 444)
                            .addComponent(lblFecharX)
                            .addGap(6, 6, 6)
                            .addComponent(lblFechar))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(154, 154, 154)
                            .addComponent(jLabel1))
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(pnlCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(pnlEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(pnlBuscarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6)
                                    .addComponent(pnlBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pnTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel9)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(pnlDataNasci, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pnlEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel14)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(pnlNome, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFecharX)
                    .addComponent(lblFechar))
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlBuscarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(6, 6, 6)
                .addComponent(pnTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(6, 6, 6)
                .addComponent(pnlNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(6, 6, 6)
                .addComponent(pnlDataNasci, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(6, 6, 6)
                .addComponent(pnlCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(7, 7, 7)
                .addComponent(pnlEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(6, 6, 6)
                .addComponent(pnlEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCadastroMouseClicked
        if(evt.isMetaDown()) {
            int linha=tbCadastro.getSelectedRow();

            if (JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(this, "Confirma a exclusão da linha "+linha, "Confirmação",
                JOptionPane.YES_NO_OPTION)) {

            ((DefaultTableModel) tbCadastro.getModel()).removeRow(tbCadastro.getSelectedRow());

        } //fim do if cx dialogo

        else {
            JOptionPane.showMessageDialog(this, "A Linha não foi Excluida!");
        }// fim do else

        }
    }//GEN-LAST:event_tbCadastroMouseClicked

    private void lblFecharXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharXMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblFecharXMouseClicked

    private void lblFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblFecharMouseClicked

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        new home_view().setVisible(true);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscaActionPerformed

    private void btnBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBibliotecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBibliotecaActionPerformed

    private void btnCadastrarLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarLivrosActionPerformed
        limparTexto();
        ativaBotao();
        ativaTexto();
        btnEditar.setEnabled(false);
    }//GEN-LAST:event_btnCadastrarLivrosActionPerformed

    private void btnFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncActionPerformed
        new register_view().setVisible(true);
    }//GEN-LAST:event_btnFuncActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmprestimoActionPerformed

    private void btnGerarRelatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatActionPerformed
        new report_view().setVisible(true);
    }//GEN-LAST:event_btnGerarRelatActionPerformed

    private void txtBuscarLivrosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarLivrosFocusGained
        txtBuscarLivros.setText("");
    }//GEN-LAST:event_txtBuscarLivrosFocusGained

    private void txtCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoFocusGained

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtTituloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTituloFocusGained

    }//GEN-LAST:event_txtTituloFocusGained

    private void txtSubtituloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubtituloFocusGained

    }//GEN-LAST:event_txtSubtituloFocusGained

    private void txtAutorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAutorFocusGained

    }//GEN-LAST:event_txtAutorFocusGained

    private void txtEditoraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEditoraFocusGained

    }//GEN-LAST:event_txtEditoraFocusGained

    private void txtEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditoraActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        //System.out.println("Linha senecionada" + tbCadastro.getSelectedRow());
        limparTexto();

        ((DefaultTableModel) tbCadastro.getModel()).removeRow(tbCadastro.getSelectedRow());

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        limparTexto();
        ativaBotao();
        ativaTexto();
        btnEditar.setEnabled(false);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        limparTexto();

        String titulo = txtTitulo.getText();
        String subtitulo = txtSubtitulo.getText();
        String autor = txtAutor.getText();
        String editora = txtEditora.getText();
        String dataPubli = txtDataPubli.getText();

        Livro l = new Livro.Builder()
            .comTitulo(titulo)
            .comSubtitulo(subtitulo)
            .comAutor(autor)
            .comEditora(editora)
            .comDataPublicacao(dataPubli)
            .build();

        livros.add(l);

        LivroDAO objlivroDAO = new LivroDAO();
        objlivroDAO.inserir(l);

        DefaultTableModel modelo = (DefaultTableModel) tbCadastro.getModel();
        modelo.addRow(new String []{txtCodigo.getText(),txtTitulo.getText(),txtSubtitulo.getText(),txtAutor.getText(),txtEditora.getText(),txtDataPubli.getText()});
        modelo.setNumRows(0);

        for(Livro livro: livros){
            modelo.addRow(new String []{livro.getTitulo(),livro.getSubtitulo(),livro.getAutor(),livro.getEditora(),livro.getDatapublicacao()});
        }
        
        txtCodigo.setText("");
        txtTitulo.setText("");
        txtSubtitulo.setText("");
        txtAutor.setText("");
        txtEditora.setText("");
        txtDataPubli.setText("");
        txtCodigo.requestFocus();

        //modelo.addRow(dados);

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtDataPubliFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataPubliFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataPubliFocusGained

    private void txtDataPubliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataPubliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataPubliActionPerformed

      private void limparTexto(){
        
        //txtSenha.setText("");
    }
    private void desativaBotao(){
        btnEditar.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }
    private void desativaTexto(){
        txtTitulo.setEnabled(false);
        txtEditora.setEnabled(false);
        txtCodigo.setEnabled(false);
        txtSubtitulo.setEnabled(false);
        txtAutor.setEnabled(false);
    }
     private void ativaBotao(){
        btnEditar.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnExcluir.setEnabled(true);
    }
    private void ativaTexto(){
        txtTitulo.setEnabled(true);
        txtEditora.setEnabled(true);
        txtCodigo.setEnabled(false);
        txtSubtitulo.setEnabled(true);
        txtAutor.setEnabled(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(books_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(books_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(books_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(books_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new books_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBiblioteca;
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCadastrarLivros;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEmprestimo;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFunc;
    private javax.swing.JButton btnGerarRelat;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblFechar;
    private javax.swing.JLabel lblFecharX;
    private javax.swing.JPanel pnTitulo;
    private javax.swing.JPanel pnlBuscar;
    private javax.swing.JPanel pnlBuscarFunc;
    private javax.swing.JPanel pnlCPF;
    private javax.swing.JPanel pnlDataNasci;
    private javax.swing.JPanel pnlEmail;
    private javax.swing.JPanel pnlEmail1;
    private javax.swing.JPanel pnlNome;
    private javax.swing.JTable tbCadastro;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtBuscarLivros;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDataPubli;
    private javax.swing.JTextField txtEditora;
    private javax.swing.JTextField txtSubtitulo;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
