/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;


import Database.UsuarioDAO;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Bussiness.Usuario;
import java.util.ArrayList;
import java.util.List;


/**
 *
 * @author Feh
 */
public class register_view extends javax.swing.JFrame {
    
     private void preencheTabela()
    {
        //Criar uma variável "LivroDAO"
        //Pegar dados dos cursos e colocar na tabela
        UsuarioDAO userDAO = new UsuarioDAO();
        List<Usuario> listaUsuario = userDAO.getUsuarios();
        
        DefaultTableModel tabelaLivros = (DefaultTableModel) tbCadastro9.getModel();
        
        //percorre a "listaLivros" e insere na Tabela
        for(Usuario u : listaUsuario){
           Object[] obj = new Object[]{
               u.getNome(), //nome
               u.getDataNasci(), //dataNasci
               u.getCpf(), //cpf
               u.getEmail(), //email
               u.getSenha() //senha
           };
           tabelaLivros.addRow(obj);
        } 
    }


    /**
     * Creates new form register_view
     */
    public register_view() {
        initComponents();
        desativaBotao();
        desativaTexto();
        setLocationRelativeTo(null);

    }

    public ArrayList<Usuario> funcionarios = new ArrayList<>();

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        tbCadastro9 = new javax.swing.JTable();
        lblX = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblCadastrarFunc8 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        btnInicio9 = new javax.swing.JButton();
        btnBusca9 = new javax.swing.JButton();
        btnBiblioteca9 = new javax.swing.JButton();
        jSeparator = new javax.swing.JSeparator();
        btnCadastrarLivros9 = new javax.swing.JButton();
        btnFunci = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnEmprestimos = new javax.swing.JButton();
        btnGerarRelato = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JSeparator();
        pnlBuscarFunc = new javax.swing.JPanel();
        txtBuscarFunc = new javax.swing.JTextField();
        pnlBuscar = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        pnCod = new javax.swing.JPanel();
        txtCod = new javax.swing.JTextField();
        pnlNome = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        pnlDataNasci = new javax.swing.JPanel();
        txtDataNasci = new javax.swing.JTextField();
        pnlCPF = new javax.swing.JPanel();
        txtCpf = new javax.swing.JTextField();
        pnlEmail = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        pnlSenha = new javax.swing.JPanel();
        txtSenha = new javax.swing.JTextField();
        pnlEditar = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        pnlExcluir = new javax.swing.JPanel();
        btnExcluir = new javax.swing.JButton();
        pnlCadastrar = new javax.swing.JPanel();
        btnCadastrar = new javax.swing.JButton();
        pnlSalvar = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        pnlCancelar = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        lblBuscarFunc = new javax.swing.JLabel();
        lblCod = new javax.swing.JLabel();
        lblDataNasci = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblCod1 = new javax.swing.JLabel();
        dcData = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel.setPreferredSize(new java.awt.Dimension(756, 791));

        tbCadastro9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Data De Nascimento", "CPF", "E-mail", "Senha"
            }
        ));
        tbCadastro9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCadastro9MouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(tbCadastro9);

        lblX.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        lblX.setForeground(new java.awt.Color(92, 95, 98));
        lblX.setText("X");
        lblX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXMouseClicked(evt);
            }
        });

        lblFecha.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(92, 95, 98));
        lblFecha.setText("Fechar");
        lblFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFechaMouseClicked(evt);
            }
        });

        lblCadastrarFunc8.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        lblCadastrarFunc8.setForeground(new java.awt.Color(102, 120, 156));
        lblCadastrarFunc8.setText("Cadastrar Funcionários");

        jPanel25.setBackground(new java.awt.Color(239, 236, 228));
        jPanel25.setPreferredSize(new java.awt.Dimension(218, 799));

        btnInicio9.setBackground(new java.awt.Color(239, 236, 228));
        btnInicio9.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        btnInicio9.setForeground(new java.awt.Color(60, 65, 70));
        btnInicio9.setText("Início");
        btnInicio9.setBorder(null);
        btnInicio9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicio9ActionPerformed(evt);
            }
        });

        btnBusca9.setBackground(new java.awt.Color(239, 236, 228));
        btnBusca9.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        btnBusca9.setForeground(new java.awt.Color(60, 65, 70));
        btnBusca9.setText("Buscar");
        btnBusca9.setBorder(null);
        btnBusca9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusca9ActionPerformed(evt);
            }
        });

        btnBiblioteca9.setBackground(new java.awt.Color(239, 236, 228));
        btnBiblioteca9.setFont(new java.awt.Font("Poppins Medium", 0, 20)); // NOI18N
        btnBiblioteca9.setForeground(new java.awt.Color(60, 65, 70));
        btnBiblioteca9.setText("Biblioteca");
        btnBiblioteca9.setBorder(null);
        btnBiblioteca9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBiblioteca9ActionPerformed(evt);
            }
        });

        jSeparator.setForeground(new java.awt.Color(102, 120, 156));

        btnCadastrarLivros9.setBackground(new java.awt.Color(239, 236, 228));
        btnCadastrarLivros9.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnCadastrarLivros9.setForeground(new java.awt.Color(60, 65, 70));
        btnCadastrarLivros9.setText("Cadastrar Livros");
        btnCadastrarLivros9.setBorder(null);
        btnCadastrarLivros9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarLivros9ActionPerformed(evt);
            }
        });

        btnFunci.setBackground(new java.awt.Color(239, 236, 228));
        btnFunci.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnFunci.setForeground(new java.awt.Color(102, 120, 156));
        btnFunci.setText("Funcionários");
        btnFunci.setBorder(null);
        btnFunci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFunciActionPerformed(evt);
            }
        });

        btnCliente.setBackground(new java.awt.Color(239, 236, 228));
        btnCliente.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnCliente.setForeground(new java.awt.Color(60, 65, 70));
        btnCliente.setText("Clientes");
        btnCliente.setBorder(null);
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        btnEmprestimos.setBackground(new java.awt.Color(239, 236, 228));
        btnEmprestimos.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnEmprestimos.setForeground(new java.awt.Color(60, 65, 70));
        btnEmprestimos.setText("Empréstimo");
        btnEmprestimos.setBorder(null);
        btnEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestimosActionPerformed(evt);
            }
        });

        btnGerarRelato.setBackground(new java.awt.Color(239, 236, 228));
        btnGerarRelato.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnGerarRelato.setForeground(new java.awt.Color(60, 65, 70));
        btnGerarRelato.setText("Gerar Relatórios");
        btnGerarRelato.setBorder(null);
        btnGerarRelato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnCadastrarLivros9))
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnFunci))
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnCliente))
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnEmprestimos))
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnGerarRelato))
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBusca9)
                            .addComponent(btnInicio9)
                            .addComponent(btnBiblioteca9))))
                .addGap(21, 21, 21))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(btnInicio9)
                .addGap(56, 56, 56)
                .addComponent(btnBusca9)
                .addGap(55, 55, 55)
                .addComponent(btnBiblioteca9)
                .addGap(50, 50, 50)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnCadastrarLivros9)
                .addGap(75, 75, 75)
                .addComponent(btnFunci)
                .addGap(72, 72, 72)
                .addComponent(btnCliente)
                .addGap(70, 70, 70)
                .addComponent(btnEmprestimos)
                .addGap(75, 75, 75)
                .addComponent(btnGerarRelato))
        );

        pnlBuscarFunc.setBackground(new java.awt.Color(240, 241, 242));
        pnlBuscarFunc.setPreferredSize(new java.awt.Dimension(408, 38));

        txtBuscarFunc.setBackground(new java.awt.Color(240, 241, 242));
        txtBuscarFunc.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        txtBuscarFunc.setForeground(new java.awt.Color(92, 95, 98));
        txtBuscarFunc.setBorder(null);
        txtBuscarFunc.setCaretColor(new java.awt.Color(92, 95, 98));
        txtBuscarFunc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarFuncFocusGained(evt);
            }
        });

        javax.swing.GroupLayout pnlBuscarFuncLayout = new javax.swing.GroupLayout(pnlBuscarFunc);
        pnlBuscarFunc.setLayout(pnlBuscarFuncLayout);
        pnlBuscarFuncLayout.setHorizontalGroup(
            pnlBuscarFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarFuncLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtBuscarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlBuscarFuncLayout.setVerticalGroup(
            pnlBuscarFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarFuncLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtBuscarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlBuscar.setBackground(new java.awt.Color(60, 65, 70));
        pnlBuscar.setForeground(new java.awt.Color(255, 255, 255));
        pnlBuscar.setPreferredSize(new java.awt.Dimension(0, 38));

        btnBuscar.setBackground(new java.awt.Color(60, 65, 70));
        btnBuscar.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(null);

        javax.swing.GroupLayout pnlBuscarLayout = new javax.swing.GroupLayout(pnlBuscar);
        pnlBuscar.setLayout(pnlBuscarLayout);
        pnlBuscarLayout.setHorizontalGroup(
            pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlBuscarLayout.setVerticalGroup(
            pnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnCod.setBackground(new java.awt.Color(240, 241, 242));
        pnCod.setPreferredSize(new java.awt.Dimension(408, 38));

        txtCod.setBackground(new java.awt.Color(240, 241, 242));
        txtCod.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        txtCod.setForeground(new java.awt.Color(92, 95, 98));
        txtCod.setBorder(null);
        txtCod.setCaretColor(new java.awt.Color(92, 95, 98));
        txtCod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodFocusGained(evt);
            }
        });
        txtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCodLayout = new javax.swing.GroupLayout(pnCod);
        pnCod.setLayout(pnCodLayout);
        pnCodLayout.setHorizontalGroup(
            pnCodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCodLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnCodLayout.setVerticalGroup(
            pnCodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCodLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlNome.setBackground(new java.awt.Color(240, 241, 242));
        pnlNome.setPreferredSize(new java.awt.Dimension(426, 38));

        txtNome.setBackground(new java.awt.Color(240, 241, 242));
        txtNome.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        txtNome.setForeground(new java.awt.Color(92, 95, 98));
        txtNome.setBorder(null);
        txtNome.setCaretColor(new java.awt.Color(92, 95, 98));
        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
        });

        javax.swing.GroupLayout pnlNomeLayout = new javax.swing.GroupLayout(pnlNome);
        pnlNome.setLayout(pnlNomeLayout);
        pnlNomeLayout.setHorizontalGroup(
            pnlNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNomeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlNomeLayout.setVerticalGroup(
            pnlNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNomeLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDataNasci.setBackground(new java.awt.Color(240, 241, 242));
        pnlDataNasci.setPreferredSize(new java.awt.Dimension(408, 38));

        txtDataNasci.setBackground(new java.awt.Color(240, 241, 242));
        txtDataNasci.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        txtDataNasci.setForeground(new java.awt.Color(92, 95, 98));
        txtDataNasci.setBorder(null);
        txtDataNasci.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDataNasciFocusGained(evt);
            }
        });

        javax.swing.GroupLayout pnlDataNasciLayout = new javax.swing.GroupLayout(pnlDataNasci);
        pnlDataNasci.setLayout(pnlDataNasciLayout);
        pnlDataNasciLayout.setHorizontalGroup(
            pnlDataNasciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDataNasciLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtDataNasci, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDataNasciLayout.setVerticalGroup(
            pnlDataNasciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDataNasciLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtDataNasci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCPF.setBackground(new java.awt.Color(240, 241, 242));
        pnlCPF.setPreferredSize(new java.awt.Dimension(408, 38));

        txtCpf.setBackground(new java.awt.Color(240, 241, 242));
        txtCpf.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        txtCpf.setForeground(new java.awt.Color(92, 95, 98));
        txtCpf.setBorder(null);
        txtCpf.setCaretColor(new java.awt.Color(92, 95, 98));
        txtCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCpfFocusGained(evt);
            }
        });

        javax.swing.GroupLayout pnlCPFLayout = new javax.swing.GroupLayout(pnlCPF);
        pnlCPF.setLayout(pnlCPFLayout);
        pnlCPFLayout.setHorizontalGroup(
            pnlCPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCPFLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlCPFLayout.setVerticalGroup(
            pnlCPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCPFLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlEmail.setBackground(new java.awt.Color(240, 241, 242));
        pnlEmail.setPreferredSize(new java.awt.Dimension(408, 38));

        txtEmail.setBackground(new java.awt.Color(240, 241, 242));
        txtEmail.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(92, 95, 98));
        txtEmail.setBorder(null);
        txtEmail.setCaretColor(new java.awt.Color(92, 95, 98));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEmailLayout = new javax.swing.GroupLayout(pnlEmail);
        pnlEmail.setLayout(pnlEmailLayout);
        pnlEmailLayout.setHorizontalGroup(
            pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmailLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlEmailLayout.setVerticalGroup(
            pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmailLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSenha.setBackground(new java.awt.Color(240, 241, 242));
        pnlSenha.setPreferredSize(new java.awt.Dimension(408, 38));

        txtSenha.setBackground(new java.awt.Color(240, 241, 242));
        txtSenha.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        txtSenha.setForeground(new java.awt.Color(92, 95, 98));
        txtSenha.setBorder(null);
        txtSenha.setCaretColor(new java.awt.Color(92, 95, 98));
        txtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenhaFocusGained(evt);
            }
        });
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSenhaLayout = new javax.swing.GroupLayout(pnlSenha);
        pnlSenha.setLayout(pnlSenhaLayout);
        pnlSenhaLayout.setHorizontalGroup(
            pnlSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSenhaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlSenhaLayout.setVerticalGroup(
            pnlSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSenhaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlEditar.setBackground(new java.awt.Color(102, 120, 156));

        btnEditar.setBackground(new java.awt.Color(102, 120, 156));
        btnEditar.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.setBorder(null);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEditarLayout = new javax.swing.GroupLayout(pnlEditar);
        pnlEditar.setLayout(pnlEditarLayout);
        pnlEditarLayout.setHorizontalGroup(
            pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
        );
        pnlEditarLayout.setVerticalGroup(
            pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlExcluir.setBackground(new java.awt.Color(102, 120, 156));

        btnExcluir.setBackground(new java.awt.Color(102, 120, 156));
        btnExcluir.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.setBorder(null);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlExcluirLayout = new javax.swing.GroupLayout(pnlExcluir);
        pnlExcluir.setLayout(pnlExcluirLayout);
        pnlExcluirLayout.setHorizontalGroup(
            pnlExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlExcluirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlExcluirLayout.setVerticalGroup(
            pnlExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlExcluirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlCadastrar.setBackground(new java.awt.Color(102, 120, 156));

        btnCadastrar.setBackground(new java.awt.Color(102, 120, 156));
        btnCadastrar.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setBorder(null);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCadastrarLayout = new javax.swing.GroupLayout(pnlCadastrar);
        pnlCadastrar.setLayout(pnlCadastrarLayout);
        pnlCadastrarLayout.setHorizontalGroup(
            pnlCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlCadastrarLayout.setVerticalGroup(
            pnlCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlSalvar.setBackground(new java.awt.Color(102, 120, 156));
        pnlSalvar.setPreferredSize(new java.awt.Dimension(123, 30));

        btnSalvar.setBackground(new java.awt.Color(102, 120, 156));
        btnSalvar.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(null);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSalvarLayout = new javax.swing.GroupLayout(pnlSalvar);
        pnlSalvar.setLayout(pnlSalvarLayout);
        pnlSalvarLayout.setHorizontalGroup(
            pnlSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
        );
        pnlSalvarLayout.setVerticalGroup(
            pnlSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSalvarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlCancelar.setBackground(new java.awt.Color(102, 120, 156));
        pnlCancelar.setPreferredSize(new java.awt.Dimension(123, 30));

        btnCancelar.setBackground(new java.awt.Color(102, 120, 156));
        btnCancelar.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);

        javax.swing.GroupLayout pnlCancelarLayout = new javax.swing.GroupLayout(pnlCancelar);
        pnlCancelar.setLayout(pnlCancelarLayout);
        pnlCancelarLayout.setHorizontalGroup(
            pnlCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCancelarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlCancelarLayout.setVerticalGroup(
            pnlCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCancelarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblBuscarFunc.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        lblBuscarFunc.setForeground(new java.awt.Color(51, 51, 51));
        lblBuscarFunc.setText("Buscar Funcionário");

        lblCod.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        lblCod.setForeground(new java.awt.Color(51, 51, 51));
        lblCod.setText("Código");

        lblDataNasci.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        lblDataNasci.setForeground(new java.awt.Color(51, 51, 51));
        lblDataNasci.setText("Data de Nascimento");

        lblCpf.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        lblCpf.setForeground(new java.awt.Color(51, 51, 51));
        lblCpf.setText("CPF");

        lblEmail.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(51, 51, 51));
        lblEmail.setText("Email");

        lblNome.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        lblNome.setForeground(new java.awt.Color(51, 51, 51));
        lblNome.setText("Nome");

        lblSenha.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(51, 51, 51));
        lblSenha.setText("Senha");

        lblCod1.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        lblCod1.setForeground(new java.awt.Color(51, 51, 51));
        lblCod1.setText("Data");

        dcData.setBackground(new java.awt.Color(240, 241, 242));
        dcData.setForeground(new java.awt.Color(92, 95, 98));
        dcData.setToolTipText("");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelLayout.createSequentialGroup()
                            .addGap(444, 444, 444)
                            .addComponent(lblX)
                            .addGap(6, 6, 6)
                            .addComponent(lblFecha))
                        .addGroup(jPanelLayout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(lblCadastrarFunc8))
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelLayout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(pnlCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelLayout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(pnlEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelLayout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblBuscarFunc)
                                .addGroup(jPanelLayout.createSequentialGroup()
                                    .addComponent(pnlBuscarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6)
                                    .addComponent(pnlBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanelLayout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDataNasci)
                                .addComponent(pnlDataNasci, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanelLayout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pnlSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelLayout.createSequentialGroup()
                                    .addComponent(pnlCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(pnlSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(pnlCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblSenha)))
                        .addGroup(jPanelLayout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCpf)
                                .addComponent(lblEmail)
                                .addGroup(jPanelLayout.createSequentialGroup()
                                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pnCod, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCod))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblCod1)
                                        .addComponent(dcData, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanelLayout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNome)
                                .addComponent(pnlNome, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(pnlEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblX)
                    .addComponent(lblFecha))
                .addGap(36, 36, 36)
                .addComponent(lblCadastrarFunc8)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblBuscarFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlBuscarFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCod)
                    .addComponent(lblCod1))
                .addGap(6, 6, 6)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dcData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnCod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNome)
                .addGap(6, 6, 6)
                .addComponent(pnlNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDataNasci)
                .addGap(6, 6, 6)
                .addComponent(pnlDataNasci, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCpf)
                .addGap(6, 6, 6)
                .addComponent(pnlCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEmail)
                .addGap(7, 7, 7)
                .addComponent(pnlEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSenha)
                .addGap(6, 6, 6)
                .addComponent(pnlSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbCadastro9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCadastro9MouseClicked
        if(evt.isMetaDown()) {
            int linha=tbCadastro9.getSelectedRow();

            if (JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(this, "Confirma a exclusão da linha "+linha, "Confirmação",
                JOptionPane.YES_NO_OPTION)) {

            ((DefaultTableModel) tbCadastro9.getModel()).removeRow(tbCadastro9.getSelectedRow());

        } //fim do if cx dialogo

        else {
            JOptionPane.showMessageDialog(this, "A Linha não foi Excluida!");
        }// fim do else

        //Selecionando tabela
        btnExcluir.setEnabled(true);
        btnEditar.setEnabled(true);

        }
    }//GEN-LAST:event_tbCadastro9MouseClicked

    private void lblXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblXMouseClicked

    private void lblFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFechaMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblFechaMouseClicked

    private void btnInicio9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicio9ActionPerformed
        new home_view().setVisible(true);
    }//GEN-LAST:event_btnInicio9ActionPerformed

    private void btnBusca9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusca9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBusca9ActionPerformed

    private void btnBiblioteca9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBiblioteca9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBiblioteca9ActionPerformed

    private void btnCadastrarLivros9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarLivros9ActionPerformed
        /* limparTexto();
        ativaBotao();
        ativaTexto();
        btnEditar.setEnabled(false);
        */

        new books_view().setVisible(true);
    }//GEN-LAST:event_btnCadastrarLivros9ActionPerformed

    private void btnFunciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFunciActionPerformed

    }//GEN-LAST:event_btnFunciActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestimosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmprestimosActionPerformed

    private void btnGerarRelatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatoActionPerformed
        new report_view().setVisible(true);
    }//GEN-LAST:event_btnGerarRelatoActionPerformed

    private void txtBuscarFuncFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarFuncFocusGained

    }//GEN-LAST:event_txtBuscarFuncFocusGained

    private void txtCodFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodFocusGained

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodActionPerformed

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained

    }//GEN-LAST:event_txtNomeFocusGained

    private void txtDataNasciFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataNasciFocusGained

    }//GEN-LAST:event_txtDataNasciFocusGained

    private void txtCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpfFocusGained

    }//GEN-LAST:event_txtCpfFocusGained

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained

    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaFocusGained

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        //System.out.println("Linha senecionada" + tbCadastro.getSelectedRow());
        limparTexto();

        ((DefaultTableModel) tbCadastro9.getModel()).removeRow(tbCadastro9.getSelectedRow());
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        limparTexto();
        ativaBotao();
        ativaTexto();
        btnEditar.setEnabled(false);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
    limparTexto();

    SimpleDateFormat dateFormat = new SimpleDateFormat ("dd-MM-yyyy");
    String Data = dateFormat.format(dcData.getDate());

     

    String nome = txtNome.getText();
    String dataNasci = txtDataNasci.getText();
    String cpf = txtCpf.getText();
    String email = txtEmail.getText();
    String senha = txtSenha.getText();

    Usuario u = new Usuario.Builder()
        .comNome(nome)
        .comDataNasci(dataNasci)
        .comCpf(cpf)
        .comEmail(email)
        .comSenha(senha)
        .build();

    UsuarioDAO objusuarioDAO = new UsuarioDAO();
    objusuarioDAO.inserir(u);

    /**
    funcionarios.add(u);

    DefaultTableModel modelo = (DefaultTableModel) tbCadastro9.getModel();
    modelo.addRow(new String []{txtNome.getText(),txtDataNasci.getText(),txtCpf.getText(),txtEmail.getText(),txtSenha.getText(),Data});
    modelo.setNumRows(0);

    for(Usuario func: funcionarios){
        modelo.addRow(new String []{func.getNome(),func.getDataNasci(),func.getCpf(),func.getEmail(),func.getSenha(),Data});
    }
    * */

        preencheTabela();
        btnExcluir.setEnabled(false);
        btnEditar.setEnabled(false);

        //modelo.addRow(dados);
    }//GEN-LAST:event_btnSalvarActionPerformed

     private void limparTexto(){
        
        //txtSenha.setText("");
    }
    private void desativaBotao(){
        btnEditar.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnExcluir.setEnabled(false);
        dcData.setDate(null);
    }
    private void desativaTexto(){
        txtCod.setEnabled(false);
        txtNome.setEnabled(false);
        txtEmail.setEnabled(false);
        txtSenha.setEnabled(false);
        txtDataNasci.setEnabled(false);
        txtCpf.setEnabled(false);
    }
     private void ativaBotao(){
        btnEditar.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnExcluir.setEnabled(true);
    }
    private void ativaTexto(){
        txtNome.setEnabled(true);
        txtEmail.setEnabled(true);
        txtSenha.setEnabled(true);
        txtDataNasci.setEnabled(true);
        txtCpf.setEnabled(true);
    }
    
    private void cancelar(){
        txtNome.setText("");
        txtEmail.setText("");
        txtSenha.setText("");
        txtDataNasci.setText("");
        txtCpf.setText("");
        txtCod.setEnabled(false);
        txtBuscarFunc.setEnabled(true);
        btnBuscar.setEnabled(true); 
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBiblioteca9;
    private javax.swing.JButton btnBusca9;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCadastrarLivros9;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEmprestimos;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFunci;
    private javax.swing.JButton btnGerarRelato;
    private javax.swing.JButton btnInicio9;
    private javax.swing.JButton btnSalvar;
    private com.toedter.calendar.JDateChooser dcData;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JLabel lblBuscarFunc;
    private javax.swing.JLabel lblCadastrarFunc8;
    private javax.swing.JLabel lblCod;
    private javax.swing.JLabel lblCod1;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDataNasci;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblX;
    private javax.swing.JPanel pnCod;
    private javax.swing.JPanel pnlBuscar;
    private javax.swing.JPanel pnlBuscarFunc;
    private javax.swing.JPanel pnlCPF;
    private javax.swing.JPanel pnlCadastrar;
    private javax.swing.JPanel pnlCancelar;
    private javax.swing.JPanel pnlDataNasci;
    private javax.swing.JPanel pnlEditar;
    private javax.swing.JPanel pnlEmail;
    private javax.swing.JPanel pnlExcluir;
    private javax.swing.JPanel pnlNome;
    private javax.swing.JPanel pnlSalvar;
    private javax.swing.JPanel pnlSenha;
    private javax.swing.JTable tbCadastro9;
    private javax.swing.JTextField txtBuscarFunc;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtDataNasci;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
