/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Database.LivroDAO;
import Bussiness.Livro;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Feh
 */
public class report_view extends javax.swing.JFrame {
    
    private void preencheTabela()
    {
        //Criar uma variável "LivroDAO"
        //Pegar dados dos cursos e colocar na tabela
        LivroDAO livroDAO = new LivroDAO();
        List<Livro> listaLivros = livroDAO.getLivros();
        
        DefaultTableModel tabelaLivros = (DefaultTableModel) tbLivro.getModel();
        
        //percorre a "listaLivros" e insere na Tabela
        for(Livro l : listaLivros){
           Object[] obj = new Object[]{
               l.getTitulo(), //titulo
               l.getSubtitulo(), //subtitulo
               l.getAutor(), //autor
               l.getEditora(), //editora
               l.getDatapublicacao() //datapubli
           };
           tabelaLivros.addRow(obj);
        } 
    }

    /**
     * Creates new form report_view
     */
    public report_view() { 
        initComponents();
        desativaBotao();
        setLocationRelativeTo(null);
        preencheTabela(); //será executado assim que abrir
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLivro = new javax.swing.JTable();
        lblFecharX = new javax.swing.JLabel();
        lblFechar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnBusca = new javax.swing.JButton();
        btnBiblioteca = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnCadastrarLivros = new javax.swing.JButton();
        btnFunc = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnEmprestimo = new javax.swing.JButton();
        btnGerarRelat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(756, 791));

        tbLivro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "Subtítulo", "Autor", "Editora", "Data da Publicação"
            }
        ));
        tbLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLivroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbLivro);

        lblFecharX.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        lblFecharX.setForeground(new java.awt.Color(92, 95, 98));
        lblFecharX.setText("X");
        lblFecharX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFecharXMouseClicked(evt);
            }
        });

        lblFechar.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        lblFechar.setForeground(new java.awt.Color(92, 95, 98));
        lblFechar.setText("Fechar");
        lblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFecharMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 120, 156));
        jLabel1.setText("Gerar Relatórios");

        jPanel1.setBackground(new java.awt.Color(239, 236, 228));
        jPanel1.setPreferredSize(new java.awt.Dimension(218, 799));

        btnInicio.setBackground(new java.awt.Color(239, 236, 228));
        btnInicio.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(60, 65, 70));
        btnInicio.setText("Início");
        btnInicio.setBorder(null);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnBusca.setBackground(new java.awt.Color(239, 236, 228));
        btnBusca.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        btnBusca.setForeground(new java.awt.Color(60, 65, 70));
        btnBusca.setText("Buscar");
        btnBusca.setBorder(null);
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });

        btnBiblioteca.setBackground(new java.awt.Color(239, 236, 228));
        btnBiblioteca.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        btnBiblioteca.setForeground(new java.awt.Color(60, 65, 70));
        btnBiblioteca.setText("Biblioteca");
        btnBiblioteca.setBorder(null);
        btnBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBibliotecaActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(102, 120, 156));

        btnCadastrarLivros.setBackground(new java.awt.Color(239, 236, 228));
        btnCadastrarLivros.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        btnCadastrarLivros.setForeground(new java.awt.Color(60, 65, 70));
        btnCadastrarLivros.setText("Cadastrar Livros");
        btnCadastrarLivros.setBorder(null);
        btnCadastrarLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarLivrosActionPerformed(evt);
            }
        });

        btnFunc.setBackground(new java.awt.Color(239, 236, 228));
        btnFunc.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        btnFunc.setForeground(new java.awt.Color(60, 65, 70));
        btnFunc.setText("Funcionários");
        btnFunc.setBorder(null);
        btnFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncActionPerformed(evt);
            }
        });

        btnClientes.setBackground(new java.awt.Color(239, 236, 228));
        btnClientes.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(60, 65, 70));
        btnClientes.setText("Clientes");
        btnClientes.setBorder(null);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnEmprestimo.setBackground(new java.awt.Color(239, 236, 228));
        btnEmprestimo.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        btnEmprestimo.setForeground(new java.awt.Color(60, 65, 70));
        btnEmprestimo.setText("Empréstimo");
        btnEmprestimo.setBorder(null);
        btnEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestimoActionPerformed(evt);
            }
        });

        btnGerarRelat.setBackground(new java.awt.Color(239, 236, 228));
        btnGerarRelat.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnGerarRelat.setForeground(new java.awt.Color(102, 120, 156));
        btnGerarRelat.setText("Gerar Relatórios");
        btnGerarRelat.setBorder(null);
        btnGerarRelat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnCadastrarLivros))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnFunc))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnClientes))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnEmprestimo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnGerarRelat))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBusca)
                            .addComponent(btnInicio)
                            .addComponent(btnBiblioteca))))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(btnInicio)
                .addGap(56, 56, 56)
                .addComponent(btnBusca)
                .addGap(55, 55, 55)
                .addComponent(btnBiblioteca)
                .addGap(51, 51, 51)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnCadastrarLivros)
                .addGap(75, 75, 75)
                .addComponent(btnFunc)
                .addGap(72, 72, 72)
                .addComponent(btnClientes)
                .addGap(70, 70, 70)
                .addComponent(btnEmprestimo)
                .addGap(75, 75, 75)
                .addComponent(btnGerarRelat)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(444, 444, 444)
                        .addComponent(lblFecharX)
                        .addGap(6, 6, 6)
                        .addComponent(lblFechar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFecharX)
                    .addComponent(lblFechar))
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbLivroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLivroMouseClicked
        if(evt.isMetaDown()) {
            int linha=tbLivro.getSelectedRow();

            if (JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(this, "Confirma a exclusão da linha "+linha, "Confirmação",
                JOptionPane.YES_NO_OPTION)) {

            ((DefaultTableModel) tbLivro.getModel()).removeRow(tbLivro.getSelectedRow());

        } //fim do if cx dialogo

        else {
            JOptionPane.showMessageDialog(this, "A Linha não foi Excluida!");
        }// fim do else

        }
    }//GEN-LAST:event_tbLivroMouseClicked

    private void lblFecharXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharXMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblFecharXMouseClicked

    private void lblFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblFecharMouseClicked

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        new home_view().setVisible(true);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscaActionPerformed

    private void btnBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBibliotecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBibliotecaActionPerformed

    private void btnCadastrarLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarLivrosActionPerformed
        new books_view().setVisible(true);
    }//GEN-LAST:event_btnCadastrarLivrosActionPerformed

    private void btnFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncActionPerformed
        new register_view().setVisible(true);
    }//GEN-LAST:event_btnFuncActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmprestimoActionPerformed

    private void btnGerarRelatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatActionPerformed

    }//GEN-LAST:event_btnGerarRelatActionPerformed
    
    private void limparTexto(){
        
        //txtSenha.setText("");
    }
    private void desativaBotao(){
       // btnEditar.setEnabled(false);
    }

     private void ativaBotao(){
       // btnEditar.setEnabled(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBiblioteca;
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnCadastrarLivros;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEmprestimo;
    private javax.swing.JButton btnFunc;
    private javax.swing.JButton btnGerarRelat;
    private javax.swing.JButton btnInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblFechar;
    private javax.swing.JLabel lblFecharX;
    private javax.swing.JTable tbLivro;
    // End of variables declaration//GEN-END:variables
}
